################################################################################
#
# Makefile
# for the documentation of the C++ project capdft
# of the Statistical Physics of Soft Matter and Complex Systems 
# research group at the Institute of Physics in Freiburg, Germany. 
#
# Author: Andreas Haertel
# Date: 21.05.2021
#
################################################################################

default: 
	@echo " Making the documentation using doxygen ... "; doxygen Doxyfile > make.log

clean: 
	@echo " Cleaning documentation ... "; rm -rf html; rm -rf latex; rm -f make.log

